apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adt-gateway.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-gateway.labels" . | nindent 4 }}
data:
    spring.zipkin.baseUrl: "http://zipkin:9411/"
    auth.service.url: "http://adt-auth:9092/"
    hrms.service.url: "http://adt-hrms:9093/"
    payroll.service.url: "http://adt-payroll:9094/"
    expense.service.url: "http://adt-expensemanagement:9095/"
    spring.jpa.hibernate.ddl-auto: none
    spring.datasource.hikari.connection-timeout: "20000"
    spring.datasource.hikari.minimum-idle: "2"
    spring.datasource.hikari.maximum-pool-size: "2"
    spring.datasource.hikari.idle-timeout: "300000"
    spring.datasource.hikari.max-lifetime: "1800000"
    spring.datasource.hikari.auto-commit: "true"